#!/bin/bash

# Silently exit if the changes are already removed
[ ! -f $1/filter/imagetopdf.c ] && exit 0

# Remove files
rm -f $1/filter/imagetopdf.c
rm -f $1/filter/pdftoijs.cxx
rm -f $1/filter/texttopdf.c
rm -f $1/filter/pdfutils.h
rm -f $1/filter/pdfutils.c
rm -f $1/filter/test_pdf1.c
rm -f $1/filter/test_pdf2.c
rm -f $1/conf/imagetopdf.convs
rm -f $1/conf/imagetopdf.types
rm -f $1/conf/pdftopdf.convs
rm -f $1/conf/pdf.types
rm -f $1/conf/texttopdf.convs
rm -f $1/data/pdf.utf-8.heavy
rm -f $1/data/pdf.utf-8.simple
rm -f $1/config-scripts/cups-pdf-filters.m4

# Remove directories
rm -rf $1/filter/fontembed
rm -rf $1/pdftopdf
rm -rf $1/pdftoopvp

cd $1

# Restore configure script
mv -f configure.in.pdf-filters configure.in
mv -f configure.pdf-filters configure
mv -f config.h.in.pdf-filters config.h.in

# Restore Makefiles
mv -f conf/Makefile.pdf-filters conf/Makefile
mv -f filter/Makefile.pdf-filters filter/Makefile
mv -f data/Makefile.pdf-filters data/Makefile
mv -f Makefile.pdf-filters Makefile
mv -f Makedefs.in.pdf-filters Makedefs.in
